// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfaYySWx5rPV-vHDOiKg9cV8StJm75I2k',
    appId: '1:103992233379:web:2bcce3799b22c84af49e16',
    messagingSenderId: '103992233379',
    projectId: 'to-do-e118d',
    authDomain: 'to-do-e118d.firebaseapp.com',
    storageBucket: 'to-do-e118d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWIL47aeeK8vS7Aw1oLgNYQEGJORtiQKo',
    appId: '1:103992233379:android:c841ef4fe1eb2bcdf49e16',
    messagingSenderId: '103992233379',
    projectId: 'to-do-e118d',
    storageBucket: 'to-do-e118d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwlo2cRIh5Z66VTjz1MMZi4lU0YVX39w',
    appId: '1:103992233379:ios:32671e4059e1c971f49e16',
    messagingSenderId: '103992233379',
    projectId: 'to-do-e118d',
    storageBucket: 'to-do-e118d.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );
}
